{
 "title": "Confluent Operator",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_labels{label_app=\"confluent-operator\"}, kubernetes_namespace)"
    }
   },
   {
    "name": "pod_name",
    "label": "Pod",
    "query": {
     "query": "label_values(controller_runtime_reconcile_time_seconds_bucket{confluent_platform=\"true\",app_kubernetes_io_name=\"confluent-operator\", kubernetes_namespace=\"$namespace\"}, kubernetes_pod_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Operator Version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "io_confluent_cfk_confluent_operator_replica_count{app=\"confluent-operator\",\nconfluent_platform=~\"true\"}\n",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Reconcile",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Reconciling Latency Over Time",
   "type": "graph",
   "description": "Length of time per reconciliation per controller",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(controller_runtime_reconcile_time_seconds_bucket{app=\"confluent-operator\",\nconfluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\", kubernetes_pod_name=~\"$pod_name\"}[5m])) by (le, controller))",
     "legendFormat": "{{controller}} "
    }
   ]
  },
  {
   "title": "Reconciling Count",
   "type": "graph",
   "description": "Total number of reconciliations per controller",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(sum(increase(controller_runtime_reconcile_total{app=\"confluent-operator\",\nconfluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\"}[4m])) by (controller, result))",
     "legendFormat": "{{controller}} - {{result }}"
    }
   ]
  },
  {
   "title": "Reconciling Error",
   "type": "graph",
   "description": "Total number of reconciliation errors per controller",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(sum(increase(confluent_operator_reconcile_errors_total{app=\"confluent-operator\",\nconfluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\"}[5m])) by (controller))",
     "legendFormat": "{{controller}} "
    }
   ]
  },
  {
   "title": "Operator K8s Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Kube API Request Rate",
   "type": "graph",
   "description": "A number of HTTP requests, partitioned by status code, method, and host.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{app=\"confluent-operator\",\nconfluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\",code=~\"2..\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{app=\"confluent-operator\",\nconfluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\",code=~\"3..\"}[5m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{app=\"confluent-operator\",\nconfluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\",code=~\"4..\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{app=\"confluent-operator\",\nconfluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\",code=~\"5..\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Post Request Latency 99th Quantile",
   "type": "graph",
   "description": "Request latency in seconds",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rest_client_request_latency_seconds_bucket{app=\"confluent-operator\",\nconfluent_platform=\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\",verb=\"POST\"}[5m])) by (verb, url, le))",
     "legendFormat": "{{ verb }} {{ url }}"
    }
   ]
  },
  {
   "title": "Get Request Latency 99th Quantile",
   "type": "graph",
   "description": "Request latency in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rest_client_request_latency_seconds_bucket{app=\"confluent-operator\",\nconfluent_platform=\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\",verb=\"GET\"}[5m])) by (verb, url, le))",
     "legendFormat": "{{ verb }} {{ url }}"
    }
   ]
  },
  {
   "title": "Patch Request Latency 99th Quantile",
   "type": "graph",
   "description": "Request latency in seconds",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rest_client_request_latency_seconds_bucket{app=\"confluent-operator\",\nconfluent_platform=\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\",verb=\"PATCH\"}[5m])) by (verb, url, le))",
     "legendFormat": "{{ verb }} {{ url }}"
    }
   ]
  },
  {
   "title": "PUT Request Latency 99th Quantile",
   "type": "graph",
   "description": "Request latency in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rest_client_request_latency_seconds_bucket{app=\"confluent-operator\",\nconfluent_platform=\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\",verb=\"PUT\"}[5m])) by (verb, url, le))",
     "legendFormat": "{{ verb }} {{ url }}"
    }
   ]
  },
  {
   "title": "Custom Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Readiness Check",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "confluent_operator_readiness_probe_count{app=\"confluent-operator\",\nconfluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Liveness Check",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "confluent_operator_liveness_probe_count{app=\"confluent-operator\",\nconfluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Secret Reference Error",
   "type": "graph",
   "description": "Total number of secretRef errors per controller",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(sum(increase(confluent_operator_secret_ref_error_total{app=\"confluent-operator\",\nconfluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\"}[5m])) by (name, namespace))",
     "legendFormat": "{{name}}  - {{namespace}} "
    }
   ]
  },
  {
   "title": "Operator Worker Queue Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Work Queue Latency",
   "type": "graph",
   "description": "How long in seconds an item stays in workqueue before being requested",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{app=\"confluent-operator\",\nconfluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\"}[5m])) by (name, le))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Work Queue, Unfinished work",
   "type": "graph",
   "description": "How many seconds of work has been done that is in progress and hasn't been observed by work_duration. Large values indicate stuck threads. One can deduce the number of stuck threads by observing the rate at which this increases",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_unfinished_work_seconds{app=\"confluent-operator\",\nconfluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\"}[5m])) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Work Queue, Longest Running ",
   "type": "graph",
   "description": "How many seconds has the longest running processor for workqueue been running",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_longest_running_processor_seconds{app=\"confluent-operator\",\nconfluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\"}[5m])) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Work Queue Retries",
   "type": "graph",
   "description": " Total number of retries handled by workqueue",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_retries_total{app=\"confluent-operator\",\nconfluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\"}[5m])) by (name, le)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Workqueue - Work Duration",
   "type": "graph",
   "description": "How long in seconds processing an item from workqueue takes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_work_duration_seconds_bucket{app=\"confluent-operator\",\nconfluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\"}[5m])) by (le, name))",
     "legendFormat": "{{name}} "
    }
   ]
  },
  {
   "title": "Work Queue Depth",
   "type": "graph",
   "description": "Current depth of workqueue",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_depth{app=\"confluent-operator\",\nconfluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\"}[5m])) by (name, le)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Work Queue Add Rate",
   "type": "graph",
   "description": "Total number of adds handled by workqueue",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{app=\"confluent-operator\",\nconfluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\"}[5m])) by (name, le)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Go Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory in Off-Heap",
   "type": "graph",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{app=\"confluent-operator\",\nconfluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "go_memstats_mspan_inuse_bytes"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{app=\"confluent-operator\",\nconfluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "go_memstats_mspan_sys_byte"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{app=\"confluent-operator\",\nconfluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "go_memstats_mcache_inuse_bytes"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{app=\"confluent-operator\",\nconfluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "go_memstats_mcache_sys_bytes"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{app=\"confluent-operator\",\nconfluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "go_memstats_buck_hash_sys_bytes"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{app=\"confluent-operator\",\nconfluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "go_memstats_gc_sys_bytes"
    },
    {
     "expr": "go_memstats_other_sys_bytes{app=\"confluent-operator\",\nconfluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\"} -  go_memstats_other_sys_bytes{app=\"confluent-operator\",\nconfluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "Other runtime allocation"
    },
    {
     "expr": "go_memstats_next_gc_bytes{app=\"confluent-operator\",\nconfluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "go_memstats_next_gc_bytes"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "graph",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 101 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{app=\"confluent-operator\",\nconfluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "go_memstats_heap_alloc_bytes"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{app=\"confluent-operator\",\nconfluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "go_memstats_heap_sys_bytes"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{app=\"confluent-operator\",\nconfluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "go_memstats_heap_idle_bytes"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{app=\"confluent-operator\",\nconfluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "go_memstats_heap_inuse_bytes"
    },
    {
     "expr": "go_memstats_heap_released_bytes{app=\"confluent-operator\",\nconfluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "go_memstats_heap_released_bytes"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "graph",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{app=\"confluent-operator\",\nconfluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "go_memstats_stack_inuse_bytes"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{app=\"confluent-operator\",\nconfluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "go_memstats_stack_sys_bytes"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "graph",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 113 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{app=\"confluent-operator\",\nconfluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "go_memstats_sys_bytes"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "graph",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 125 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{app=\"confluent-operator\",\nconfluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\"}[5m])",
     "legendFormat": "go_memstats_mallocs_total"
    }
   ]
  },
  {
   "title": "Rate of a Pointer Dereferences (2m)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 11, "x": 11, "y": 125 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_lookups_total{app=\"confluent-operator\",\nconfluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\"}[2m])",
     "legendFormat": "go_memstats_lookups_total"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 137 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{app=\"confluent-operator\",\nconfluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\"}",
     "legendFormat": "go_goroutines"
    }
   ]
  },
  {
   "title": "GC Duration Mean",
   "type": "graph",
   "description": " A summary of the GC invocation durations.",
   "gridPos": { "h": 12, "w": 11, "x": 11, "y": 137 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_gc_duration_seconds_sum{app=\"confluent-operator\",confluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\"}[5m])) / sum(rate(go_gc_duration_seconds_count{app=\"confluent-operator\",confluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\"}[5m]))",
     "legendFormat": "gc-duration-mean"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "graph",
   "gridPos": { "h": 12, "w": 11, "x": 11, "y": 149 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{app=\"confluent-operator\",\nconfluent_platform=~\"true\",kubernetes_namespace=~\"$namespace\",kubernetes_pod_name=~\"$pod_name\"}[2m])",
     "legendFormat": "go_memstats_alloc_bytes_total"
    }
   ]
  }
 ]
}